name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install Development Dependencies
      run: |
        pip install .[dev]

    - name: Analyze Syntax
      run: |
        echo "Running linters ..."
        invoke lint

#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.12'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install .[dev]
#
#    - name: Run tests
#      run: |
#        echo "Running tests ..."
#        invoke test
#
#
#  build:
#    runs-on: ubuntu-latest
#    needs:
#      - lint
#      - test
#
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4
#
#    - name: Set up Python
#      uses: actions/setup-python@v5
#      with:
#        python-version: '3.12'
#
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install setuptools wheel
#        pip install .[dev]
#
#    - name: Run tests
#      run: |
#        echo "Running tests ..."
#        invoke test
